ARG GCC_VERSION=
FROM gcc:${GCC_VERSION}

ARG CMAKE_VERSION=3.14.0
SHELL ["bash", "-c"]

RUN set -euo pipefail && \
    # Install deps
    apt-get update && apt-get install -y --no-install-recommends ca-certificates wget; \
    # The sh file is too big to do direct pipe, so save to file and run from there instead
    wget https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}-Linux-x86_64.sh; \
    bash cmake-${CMAKE_VERSION}-Linux-x86_64.sh --skip-license --prefix=/usr/local; \
    cmake --version; \
    rm cmake-${CMAKE_VERSION}-Linux-x86_64.sh; \
    # Clean up deps
    apt-get remove -y wget; \
    rm -rf /var/cache/apt; \
    :
